# Generated by Django 6.0 on 2026-03-21 05:46

from django.conf import settings
from django.db import migrations, models


def migrate_roles_forward(apps, schema_editor):
    StaffProfile = apps.get_model("users", "StaffProfile")
    app_label, model_name = settings.AUTH_USER_MODEL.split(".")
    User = apps.get_model(app_label, model_name)

    StaffProfile.objects.filter(role="owner").update(role="admin")
    StaffProfile.objects.filter(role="staff").update(role="cashier")

    admin_user_ids = list(
        StaffProfile.objects.filter(role="admin", is_active=True).values_list("user_id", flat=True)
    )
    cashier_user_ids = list(
        StaffProfile.objects.exclude(user_id__in=admin_user_ids).values_list("user_id", flat=True)
    )

    if admin_user_ids:
        User.objects.filter(id__in=admin_user_ids, is_superuser=False).update(is_staff=True)
    if cashier_user_ids:
        User.objects.filter(id__in=cashier_user_ids, is_superuser=False).update(is_staff=False)


def migrate_roles_backward(apps, schema_editor):
    StaffProfile = apps.get_model("users", "StaffProfile")
    app_label, model_name = settings.AUTH_USER_MODEL.split(".")
    User = apps.get_model(app_label, model_name)

    StaffProfile.objects.filter(role="admin").update(role="owner")
    StaffProfile.objects.filter(role="cashier").update(role="staff")

    owner_user_ids = list(
        StaffProfile.objects.filter(role="owner", is_active=True).values_list("user_id", flat=True)
    )
    staff_user_ids = list(
        StaffProfile.objects.exclude(user_id__in=owner_user_ids).values_list("user_id", flat=True)
    )

    if owner_user_ids:
        User.objects.filter(id__in=owner_user_ids, is_superuser=False).update(is_staff=True)
    if staff_user_ids:
        User.objects.filter(id__in=staff_user_ids, is_superuser=False).update(is_staff=False)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('cashier', 'Cashier')], default='cashier', max_length=10),
        ),
        migrations.RunPython(migrate_roles_forward, migrate_roles_backward),
    ]
