services:
  db:
    image: postgres:16
    container_name: uzbekburger_db
    environment:
      POSTGRES_DB: uzbekburger
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - pgdata:/var/lib/postgresql/data

  init:
    build: .
    container_name: uzbekburger_init
    env_file: [.env]
    depends_on: [db]
    volumes:
      - .:/app
      - staticfiles:/app/staticfiles
      - ./media:/app/media
    command: >
      sh -c "
      until python -c \"import socket; s=socket.socket(); s.settimeout(1); s.connect(('db', 5432))\" 2>/dev/null; do sleep 1; done;
      python manage.py migrate &&
      python manage.py collectstatic --noinput
      "
    restart: "no"

  web_pos:
    build: .
    container_name: uzbekburger_web_pos
    env_file: [.env]
    environment:
      ROOT_URLCONF: config.urls_pos
      POS_MODE: "1"
    depends_on:
      init:
        condition: service_completed_successfully
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - .:/app
      - staticfiles:/app/staticfiles
      - ./media:/app/media
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 60

  web_landing:
    build: .
    container_name: uzbekburger_web_landing
    env_file: [.env]
    environment:
      ROOT_URLCONF: config.urls_landing
      POS_MODE: "0"
    depends_on:
      init:
        condition: service_completed_successfully
    ports:
      - "127.0.0.1:8001:8001"
    volumes:
      - .:/app
      - staticfiles:/app/staticfiles
      - ./media:/app/media
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8001 --workers 2 --timeout 60

volumes:
  pgdata:
  staticfiles:
