# Generated by Django 6.0 on 2026-01-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='map_iframe',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='public_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='branch',
            name='public_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='branch',
            name='show_on_landing',
            field=models.BooleanField(default=True),
        ),
    ]
