# Generated by Django 6.0 on 2026-02-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_landing_instagram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingsettings',
            name='email',
        ),
        migrations.AlterField(
            model_name='landingsettings',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='landingsettings',
            name='telegram',
            field=models.URLField(blank=True),
        ),
    ]
