# Generated by Django 6.0 on 2026-01-16 11:20

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('kind', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank', 'Bank'), ('other', 'Other')], default='cash', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('balance_cache', models.BigIntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_accounts', to='core.branch')),
            ],
            options={
                'verbose_name': 'Kassa',
                'verbose_name_plural': 'Kassalar',
            },
        ),
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('in', 'IN'), ('out', 'OUT')], max_length=5)),
                ('txn_type', models.CharField(choices=[('sale', 'Sale'), ('import', 'Import'), ('expense', 'Expense'), ('transfer', 'Transfer'), ('adjust', 'Adjust')], max_length=12)),
                ('amount', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('occurred_at', models.DateTimeField()),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('ref_type', models.CharField(blank=True, max_length=30, null=True)),
                ('ref_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_txns', to='core.branch')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='txns', to='finance.moneyaccount')),
            ],
            options={
                'verbose_name': "Pul o'tkazmasi",
                'verbose_name_plural': "Pul o'tkazmalari",
            },
        ),
        migrations.AddConstraint(
            model_name='moneyaccount',
            constraint=models.UniqueConstraint(fields=('branch', 'name'), name='uniq_branch_account_name'),
        ),
        migrations.AddIndex(
            model_name='cashtransaction',
            index=models.Index(fields=['branch', 'occurred_at'], name='finance_cas_branch__424ff0_idx'),
        ),
        migrations.AddIndex(
            model_name='cashtransaction',
            index=models.Index(fields=['account', 'occurred_at'], name='finance_cas_account_f62691_idx'),
        ),
    ]
