# Generated by Django 6.0 on 2026-03-21 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_branch_working_hours'),
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashtransaction',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='reason',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='txn_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('import', 'Import'), ('expense', 'Expense'), ('transfer', 'Transfer'), ('opening_balance', 'Opening balance'), ('cash_adjustment', 'Cash adjustment'), ('cash_in', 'Cash in'), ('cash_out', 'Cash out'), ('adjust', 'Legacy adjust')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='cashtransaction',
            index=models.Index(fields=['txn_type', 'occurred_at'], name='finance_cas_txn_typ_90a107_idx'),
        ),
    ]
