# Generated by Django 6.0 on 2026-01-16 11:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0001_initial'),
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockImport',
            fields=[
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted')], default='DRAFT', max_length=10)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_imports', to='core.branch')),
                ('cash_txn', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.cashtransaction')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_stock_imports', to=settings.AUTH_USER_MODEL)),
                ('paid_from_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='imports_paid', to='finance.moneyaccount')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_stock_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ombor importi',
                'verbose_name_plural': 'Ombor importlari',
            },
        ),
        migrations.CreateModel(
            name='BranchProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stock_qty', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('avg_unit_cost', models.BigIntegerField(default=0)),
                ('last_unit_cost', models.BigIntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_products', to='core.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_products', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Filial mahsuloti',
                'verbose_name_plural': 'Filial mahsulotlari',
                'constraints': [models.UniqueConstraint(fields=('branch', 'product'), name='uniq_branch_product')],
            },
        ),
        migrations.CreateModel(
            name='StockImportItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qty', models.DecimalField(decimal_places=3, max_digits=14)),
                ('line_total_cost', models.BigIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
                ('stock_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockimport')),
            ],
            options={
                'verbose_name': "Ombor import bo'lagi",
                'verbose_name_plural': "Ombor import bo'laklari",
                'constraints': [models.UniqueConstraint(fields=('stock_import', 'product'), name='uniq_import_product')],
            },
        ),
    ]
