# Generated by Django 6.0 on 2026-01-07 04:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_product_avg_unit_cost_and_more'),
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockimportitem',
            name='stock_import',
        ),
        migrations.RemoveField(
            model_name='stockimportitem',
            name='product',
        ),
        migrations.CreateModel(
            name='BranchProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stock_qty', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('avg_unit_cost', models.BigIntegerField(default=0)),
                ('last_unit_cost', models.BigIntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_products', to='core.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_products', to='catalog.product')),
            ],
        ),
        migrations.DeleteModel(
            name='StockImport',
        ),
        migrations.DeleteModel(
            name='StockImportItem',
        ),
        migrations.AddConstraint(
            model_name='branchproduct',
            constraint=models.UniqueConstraint(fields=('branch', 'product'), name='uniq_branch_product'),
        ),
    ]
