# Generated by Django 6.0 on 2026-01-07 04:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_product_avg_unit_cost_and_more'),
        ('core', '0001_initial'),
        ('inventory', '0002_remove_stockimportitem_stock_import_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_imports', to='core.branch')),
            ],
        ),
        migrations.CreateModel(
            name='StockImportItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qty', models.DecimalField(decimal_places=3, max_digits=14)),
                ('line_total_cost', models.BigIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
                ('stock_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockimport')),
            ],
        ),
    ]
