# Generated by Django 6.0 on 2026-01-07 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_product_avg_unit_cost_and_more'),
        ('inventory', '0003_stockimport_stockimportitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockimport',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted')], default='DRAFT', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='stockimportitem',
            constraint=models.UniqueConstraint(fields=('stock_import', 'product'), name='uniq_import_product'),
        ),
    ]
