# Generated by Django 6.0 on 2026-01-07 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('inventory', '0004_stockimport_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockimport',
            name='cash_txn',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.cashtransaction'),
        ),
        migrations.AddField(
            model_name='stockimport',
            name='paid_from_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='imports_paid', to='finance.moneyaccount'),
        ),
    ]
