"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG")

ALLOWED_HOSTS = [h.strip() for h in os.getenv("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",") if h.strip()]

CSRF_TRUSTED_ORIGINS = ["http://64.227.156.11:8000"]
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
# Application definition

# Optional dependency: django-jazzmin (Admin UI theme)
HAS_JAZZMIN = False
try:
    import jazzmin  # noqa: F401
    HAS_JAZZMIN = True
except Exception:
    HAS_JAZZMIN = False

INSTALLED_APPS = ([] if not HAS_JAZZMIN else ['jazzmin']) + [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    "catalog",
    "inventory",
    "menu",
    "core",
    "finance.apps.FinanceConfig",
    "sales",
    "users",
]



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    "django.middleware.locale.LocaleMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.AdminGuardMiddleware',
    "core.middleware.ActiveBranchMiddleware",  # ✅ qo'shildi
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.app_context",
            ],
            "libraries": {  # ✅ qo'lda ro'yxatdan o'tkazamiz
                "money": "core.templatetags.money",
            },
        },
    },
]


WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    "default": dj_database_url.parse(
        os.getenv("DATABASE_URL", "postgres://postgres:root@db:5432/uzbekburger"),
        conn_max_age=60,
    )
}



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'uz'

TIME_ZONE = 'Asia/Tashkent'

USE_I18N = True

USE_TZ = True
LANGUAGES = [
    ("uz", "O'zbekcha")
]

LOCALE_PATHS = [
    BASE_DIR / "locale",
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = os.getenv("STATIC_URL", "/static/")
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = os.getenv("STATIC_ROOT", str(BASE_DIR / "staticfiles"))

MEDIA_URL = os.getenv("MEDIA_URL", "/media/")
MEDIA_ROOT = os.getenv("MEDIA_ROOT", str(BASE_DIR / "media"))



# =========================
# JAZZMIN (Admin UI theme)
# =========================
JAZZMIN_SETTINGS = {
    "site_title": "UzbekBurger Admin",
    "site_header": "UzbekBurger — Boshqaruv paneli",
    "site_brand": "UzbekBurger",
    "welcome_sign": "Boshqaruv paneliga xush kelibsiz",
    "copyright": "UzbekBurger",
    # Logos (static/)
    "site_logo": "img/favicon.svg",
    "login_logo": "img/favicon.svg",
    "site_logo_classes": "img-circle",
    "custom_css": "admin/ub_admin.css",
    "changeform_format":"single",
    # Top menu
    "topmenu_links": [
        {"name": "POS", "url": "/pos/"},
        {"model": "auth.User"},
    ],
    # Sidebar menu icons (optional)
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "core.branch": "fas fa-store",
        "catalog.product": "fas fa-box",
        "inventory.branchproduct": "fas fa-warehouse",
        "inventory.stockimport": "fas fa-truck-loading",
        "menu.food": "fas fa-hamburger",
        "sales.order": "fas fa-receipt",
        "finance.moneyaccount": "fas fa-cash-register",
        "finance.cashtransaction": "fas fa-money-bill-wave",
        "users.staffprofile": "fas fa-user-shield",
    },
}

JAZZMIN_UI_TWEAKS = {
    "theme": "darkly",                 # bazaviy dark
    "navbar": "navbar-dark",
    "navbar_fixed": True,

    "sidebar": "sidebar-dark-primary",
    "sidebar_fixed": True,

    "accent": "accent-success",        # yashil accent
    "brand_small_text": False,

    "button_classes": {
        "primary": "btn btn-success",
        "secondary": "btn btn-outline-light",
        "info": "btn btn-outline-info",
        "warning": "btn btn-outline-warning",
        "danger": "btn btn-outline-danger",
        "success": "btn btn-success",
    }
}




LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/accounts/login/"
