# Generated by Django 6.0 on 2026-01-06 14:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('count_type', models.CharField(choices=[('pcs', 'pcs'), ('kg', 'kg'), ('l', 'l'), ('gr', 'gr'), ('ml', 'ml')], max_length=10)),
                ('sku', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('barcode', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('stock_qty', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('avg_unit_cost', models.BigIntegerField(default=0)),
                ('last_unit_cost', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
