# Generated by Django 6.0 on 2026-01-07 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='avg_unit_cost',
        ),
        migrations.RemoveField(
            model_name='product',
            name='last_unit_cost',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_qty',
        ),
    ]
