# Generated by Django 6.0 on 2026-01-16 11:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('FASTFOOD', 'Fastfood'), ('DRINK', 'Ichimlik'), ('SET', 'Set')], default='FASTFOOD', max_length=20)),
                ('name', models.CharField(max_length=80)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_categories', to='core.branch')),
            ],
            options={
                'verbose_name': 'Taom turi',
                'verbose_name_plural': 'Taom turlari',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('FASTFOOD', 'Fastfood'), ('DRINK', 'Ichimlik'), ('SET', 'Set')], default='FASTFOOD', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='foods/')),
                ('sell_price', models.BigIntegerField(default=0)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='core.branch')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foods', to='menu.foodcategory')),
            ],
            options={
                'verbose_name': 'Taom',
                'verbose_name_plural': 'Taomlar',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qty', models.DecimalField(decimal_places=3, max_digits=14)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.food')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
            ],
            options={
                'verbose_name': 'Taom mahsuloti',
                'verbose_name_plural': 'Taom mahsulotlari',
            },
        ),
        migrations.AddConstraint(
            model_name='foodcategory',
            constraint=models.UniqueConstraint(fields=('branch', 'type', 'name'), name='uniq_branch_foodcategory_typename'),
        ),
        migrations.AddConstraint(
            model_name='food',
            constraint=models.UniqueConstraint(fields=('branch', 'name'), name='uniq_branch_food_name'),
        ),
        migrations.AlterUniqueTogether(
            name='fooditem',
            unique_together={('food', 'product')},
        ),
    ]
