# Generated by Django 6.0 on 2026-01-21 12:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('food', models.ForeignKey(limit_choices_to={'type__in': ['FASTFOOD', 'DRINK']}, on_delete=django.db.models.deletion.PROTECT, related_name='as_set_component', to='menu.food')),
                ('set_food', models.ForeignKey(limit_choices_to={'type': 'SET'}, on_delete=django.db.models.deletion.CASCADE, related_name='set_items', to='menu.food')),
            ],
            options={
                'verbose_name': 'Set elementi',
                'verbose_name_plural': 'Set elementlari',
                'unique_together': {('set_food', 'food')},
            },
        ),
    ]
