# Generated by Django 6.0 on 2026-01-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stock_applied',
            field=models.BooleanField(default=False),
        ),
    ]
