# Generated by Django 6.0 on 2026-03-21 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_order_options_order_cogs_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Yangi'), ('paid', "To'langan"), ('canceled', 'Bekor qilingan')], default='draft', max_length=12),
        ),
    ]
